### ISSUE TITLE
Proper handling of optional attributes

### ISSUE THREAD

**Issue by Mateiadrielrafael** [adisbladis/korora#5]
Right now, I am simply setting `total` to `false`, and then manually adding an invariant which checks whether the required properties are there.

It would also be nice to offer some built in useful invariants. A few I found myself using often were "prop A implies prop B" and "props A and B are mutually exclusive"

**Comment by adisbladis** [comment]
I was briefly considering overloading the meaning of `optional`, to mean not just mean `null or T` but to mean `optional attribute`.

Maybe `optional` should be configurable to be able to express optional attributes, but I found the UX of having to override each optional declaration terrible.

**Comment by adisbladis** [comment]
Closed by fdb14aee55b1cf7a0d166cc1cbb879dd4dfa7e34
